-- Este codigo se esforça para criar uma versão adaptada 
-- do BD exposto no Capítulo 1 do livro do Navathe.
-- Aqui, faço a criação das tabelas no padrão ANSI SQL. 
--  

CREATE DATABASE universidade_bd01;

CONNECT TO universidade_bd01;


CREATE TABLE ALUNO (
    NOME           VARCHAR(80)    NOT NULL,
    NUMERO_ALUNO   INTEGER        NOT NULL,
    TIPO_ALUNO     INTEGER        NOT NULL,
    CURSO          VARCHAR(10)    NOT NULL,
    PRIMARY KEY (NUMERO_ALUNO)
);

CREATE TABLE DISCIPLINA (
    NOME_DISCIPLINA     VARCHAR(120) NOT NULL,
    NUMERO_DISCIPLINA   VARCHAR(10)  NOT NULL,
    CREDITOS            INTEGER      NOT NULL,
    DEPARTAMENTO        VARCHAR(10)  NOT NULL,
    PRIMARY KEY (NUMERO_DISCIPLINA)
);

CREATE TABLE TURMA (
    IDENTIFICADOR_TURMA   INTEGER      NOT NULL,
    NUMERO_DISCIPLINA     VARCHAR(10)  NOT NULL,
    SEMESTRE              VARCHAR(10)  NOT NULL,
    ANO                   CHAR(2)      NOT NULL,   -- Mantendo formato '07', '08'
    PROFESSOR             VARCHAR(80)  NOT NULL,
    PRIMARY KEY (IDENTIFICADOR_TURMA),
    FOREIGN KEY (NUMERO_DISCIPLINA)
        REFERENCES DISCIPLINA (NUMERO_DISCIPLINA)
);

CREATE TABLE REGISTRO_NOTA (
    NUMERO_ALUNO        INTEGER     NOT NULL,
    IDENTIFICADOR_TURMA INTEGER     NOT NULL,
    NOTA                CHAR(1)     NOT NULL,
    PRIMARY KEY (NUMERO_ALUNO, IDENTIFICADOR_TURMA),
    FOREIGN KEY (NUMERO_ALUNO)
        REFERENCES ALUNO (NUMERO_ALUNO),
    FOREIGN KEY (IDENTIFICADOR_TURMA)
        REFERENCES TURMA (IDENTIFICADOR_TURMA)
);

CREATE TABLE PRE_REQUISITO (
    NUMERO_DISCIPLINA       VARCHAR(10) NOT NULL,
    NUMERO_PRE_REQUISITO    VARCHAR(10) NOT NULL,
    PRIMARY KEY (NUMERO_DISCIPLINA, NUMERO_PRE_REQUISITO),
    FOREIGN KEY (NUMERO_DISCIPLINA)
        REFERENCES DISCIPLINA (NUMERO_DISCIPLINA),
    FOREIGN KEY (NUMERO_PRE_REQUISITO)
        REFERENCES DISCIPLINA (NUMERO_DISCIPLINA)
);

-- Inserção dos dados de exemplo

INSERT INTO ALUNO (NOME, NUMERO_ALUNO, TIPO_ALUNO, CURSO) VALUES
('Silva', 17, 1, 'CC'),
('Braga', 8, 2, 'CC');

INSERT INTO DISCIPLINA (NOME_DISCIPLINA, NUMERO_DISCIPLINA, CREDITOS, DEPARTAMENTO) VALUES
('INTRODUÇÃO À LÓGICA DE PROGRAMAÇÃO', 'MATA37', 3, 'CC'),
('INTELIGÊNCIA ARTIFICIAL', 'MATA64', 4, 'CC'),
('INTELIGÊNCIA ARTIFICIAL', 'MAT054', 4, 'LC'),
('BANCO DE DADOS', 'MATA60', 4, 'CC');

INSERT INTO TURMA (IDENTIFICADOR_TURMA, NUMERO_DISCIPLINA, SEMESTRE, ANO, PROFESSOR) VALUES
(85, 'MATA60', 'Segundo', '04', 'Robespierre'),
(92, 'MATA64',  'Segundo', '05', 'Ricardo'),
(102,'MAT054',  'Primeiro','05', 'Flavio'),
(112,'MATA60', 'Primeiro', '04', 'Daniela'),
(119,'MATA37',  'Segundo', '01', 'Rubisley'),
(135, 'MATA64',  'Segundo', '05', 'Tatiane');

INSERT INTO REGISTRO_NOTA (NUMERO_ALUNO, IDENTIFICADOR_TURMA, NOTA) VALUES
(17, 112, '7'),
(17, 119, '5'),
( 8,  85, '6'),
( 8,  92, '7'),
( 8, 102, '10'),
( 8, 135, '9');

-- minha ideia aqui foi garantir que 
INSERT INTO PRE_REQUISITO (NUMERO_DISCIPLINA, NUMERO_PRE_REQUISITO) VALUES
('MATA64', 'MATA37'),
('MATA60', 'MATA37');
